### ISSUE TITLE
Totally waste of time 

### ISSUE THREAD

**Issue by Digmoy** [0xsanchit/MongoDbRealmCourse_Android#1]
Not helpful at all. The complete tutorial code is not provided here.

**Comment by 0xsanchit** [comment]
Sorry for the issue , you can check my other repositories too . Also , I will update this in sometime . The youtube video has all the code you need though

**Comment by Digmoy** [comment]
As mentioned earlier,I needed the full code for implementation in my
project but I am unable to access it. Please kindly provide the full code
of the given project
